export enum TODO_STATUS {
  SCHEDULED = "SCHEDULED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED"
};

export enum TODO_TYPE {
  PERSONAL = "PERSONAL",
  GROUP = "GROUP"
}

export enum MEMBER_ROLE {
  MEMBER = "MEMBER",
  ADMIN = "ADMIN"
}

export enum MEMBER_INVITATION_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED"
}