export type TODO_STATUS = "SCHEDULED" | "IN_PROGRESS" | "COMPLETED" | "CANCELED";
export type TODO_TYPE = "PERSONAL" | "GROUP";
export type MEMBER_ROLE = "MEMBER" | "ADMIN";
export type MEMEBER_INVITATION_STATUS = "PENDING" | "ACCEPTED" | "REJECTED";